# Generated by Django 5.2.8 on 2025-11-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField()),
                ('location_filter', models.CharField(blank=True, max_length=255, null=True)),
                ('response_summary', models.TextField()),
                ('chart_data', models.JSONField()),
                ('table_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('year', models.IntegerField()),
                ('demand', models.IntegerField(default=0)),
                ('demand_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'location'],
                'indexes': [models.Index(fields=['location', 'year'], name='api_propert_locatio_7e8cd2_idx'), models.Index(fields=['property_type'], name='api_propert_propert_80e661_idx')],
            },
        ),
    ]
